version: 5.1.0
variant: default
head:
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        image: 
    rss: /atom.xml
navbar:
    menu:
        Home: /
        Timeline: /archives
        Categories: /categories
        Tags: /tags
        My works: /works
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
        CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
        ShareAlike:
            icon: fab fa-creative-commons-sa
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
search:
    type: insight
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: right
        type: profile
        author: Jack Works
        author_title: 🧙‍♂️
        location: 🌎
        avatar: https://avatars.githubusercontent.com/u/5390719?s=460&v=4
        avatar_rounded: true
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/Jack-Works
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/jackworks_asref/
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: right
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: right
        type: tags
plugins:
    animejs: false
    back_to_top: true
    gallery: true
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
